### ISSUE TITLE
Problem: kinsumer table names can't be changed

### ISSUE THREAD

**Issue by sevein** [JiscRDSS/rdss-archivematica-channel-adapter#37]
In Kinsumer, the three internal state tables are named after the application name which have not been made configurable yet - we name it as `rdss_am` - so the tables are named as `rdss_am_checkpoints`, `rdss_am_clients` and `rdss_am_metadata`.

**Comment by sevein** [comment]
#38 solves the problem. The application name can be defined using the new environment variable `RDSS_ARCHIVEMATICA_ADAPTER_BROKER.KINESIS.APP_NAME`, e.g. `RDSS_ARCHIVEMATICA_ADAPTER_BROKER.KINESIS.APP_NAME=rdss_am_adapter_480`.

**Comment by lower29** [comment]
Can this be closed now that #40 has been merged?

**Comment by sevein** [comment]
Yay!
