### ISSUE TITLE
Problem: files in AIP are named according to the storage location filename

### ISSUE THREAD

**Issue by sevein** [JiscRDSS/rdss-archivematica-channel-adapter#56]
The channel adapter names the files in the transfer after the filename extracted from the `fileStorageLocation` property, e.g. `http://domain.tld/foobar.jpg` => `foobar.jpg`.
Instaed, we should name it after the value found in the `fileName` property.

**Comment by mjaddis** [comment]
https://jiscdev.atlassian.net/browse/RDSSARK-271

**Comment by sevein** [comment]
https://jiscdev.atlassian.net/browse/RDSSARK-270
