### ISSUE TITLE
Problem: message decoding and validation tests are skipped

### ISSUE THREAD

**Issue by lower29** [JiscRDSS/rdss-archivematica-channel-adapter#79]
In PR #76 we changed the schema validation introduced in PR #70 to download the schema specification from the [rdss-message-api-specification](https://github.com/JiscRDSS/rdss-message-api-specification) repo. In doing so, we lost control of the fixtures for validation tests, so had no choice but to skip some of the tests we would like to do.

Once PRs https://github.com/JiscRDSS/rdss-message-api-specification/pull/67 and https://github.com/JiscRDSS/rdss-message-api-specification/pull/77 have been merged and released as part of a stable API version, we should re-instate these skipped elements of the tests so that we're able to confirm our implementation validates the reference messages correctly.

**Comment by sevein** [comment]
This is already fixed!
